name: Build Ilot14

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize devkit environment
        shell: bash
        run: |
          source /etc/profile
          echo "$DEVKITPRO"
          aarch64-none-elf-g++ --version

      - name: Build
        shell: bash
        run: |
          source /etc/profile
          make

      - name: Upload NRO
        uses: actions/upload-artifact@v4
        with:
          name: Ilot14
          path: "*.nro"
          if-no-files-found: error
